### ISSUE TITLE
Error when running the sample: TypeError: unsupported operand type(s) for /: 'Range' and 'type'

### ISSUE THREAD

**Issue by g3rzi** [sogeti-esec-lab/RPCForge#1]
When I run the sample from [your usage](https://github.com/sogeti-esec-lab/RPCForge#usage) it failed with the following error:  
```
TypeError: unsupported operand type(s) for /: 'Range' and 'type'
```

It happens in row 17:  
![image](https://user-images.githubusercontent.com/11998736/143021496-3077e510-84db-455f-88a8-d7d4bd149c5f.png)

What is the meaning of `/` when you run:  
```
Range(0,65535) / NdrLong
```

**Comment by masthoon** [comment]
The exception is probably due to Python 3 (\_\_div\_\_ vs \_\_truediv\_\_ overload).
There is no maintainer to port this tool to Python 3.
So, I will archive the repository, feel free to fork it.
